set ambiwidth=double
set guifont=Ricty\ for\ Powerline:h13
set lines=48
set columns=185
" scrollbar is always off
set guioptions-=rL
" not guitablabel
set guioptions-=e
set modifiable
set write
set nobackup
set mouse=""

" for railscasts
"colorscheme railscasts
"highlight LineNr guibg=#000000 guifg=#C6FBF5
"highlight TabLine guibg=#777777
"highlight TabLineSel guibg=#3F5F85
"hi Folded gui=bold term=standout guibg=#191919 guifg=#969581
"hi NonText gui=bold term=underline guifg=#DEA04B
"hi PreProc guifg=#9499C4
"hi Search guibg=#0088CC guifg=#000000
"hi PmenuSel guibg=#000000 guifg=#666666
"hi Special guifg=#D35D4F
"hi Type guifg=#D35D4F
"set transparency=15

" for tomorrow-night
colorscheme Tomorrow-Night-Eighties
set cursorline
set transparency=10
highlight LineNr guibg=#2d2d2d guifg=#C6FBF5
