ZSH=$HOME/.oh-my-zsh
ZSH_THEME="miloshadzic"
source $ZSH/oh-my-zsh.sh

plugins=(git)

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# move dirs without cd
setopt AUTO_CD

# move between dirs
cdpath=(.. ~ ~/src)

# refresh
alias refresh="source dotfiles/home/zshrc"

# Brew command
alias brew="env PATH=${PATH/\/Users\/Jinda\/\.pyenv\/shims:?/} brew"

# open apps
alias vi='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
alias chrome='open -a Google\ Chrome'
alias safari='open -a Safari'
alias firefox='open -a Firefox'
alias slack='open -a Slack'
alias evernote='open -a Evernote'
alias line='open -a LINE'
alias skype='open -a Skype'
alias gyazo='open -a Gyazo'
alias skitch='open -a Skitch'
alias hipchat='open -a Hipchat'
alias photoshop='open -a Adobe\ Photoshop\ CC\ 2015'
alias illustrator='open -a Adobe\ Illustrator\ CC\ 2015'
alias notes='open -a notes'
alias wunderlist='open -a Wunderlist'
alias xcode='open -a Xcode'
alias tweetdeck='open -a TweetDeck'
alias boxy='open -a Boxy'

# weather
alias wtokyo="curl -4 wttr.in/tokyo"

# move file to trash
alias rm="rmtrash"

# Git
alias g='git'
alias s='git s'
alias m='git checkout master'
alias d='git d'

# Unix
alias ..='cd ..'
alias t='tmux'
alias grep='grep --color=auto'

# Ruby
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'

# Haskell
alias ghc='stack ghc'
alias ghci='stack ghci'
alias runhaskell='stack runhaskell'

if which pyenv > /dev/null; then
  export PYENV_ROOT="${HOME}/.pyenv"
  export PATH=${PYENV_ROOT}/shims:${PATH}
  eval "$(pyenv init -)";
fi
if which plenv > /dev/null; then
  export PLENV_ROOT="${HOME}/.plenv"
  export PATH=${PLENV_ROOT}/shims:${PATH}
  eval "$(plenv init -)";
fi
if which mysqlenv > /dev/null; then
  export MYSQLENV_ROOT="${HOME}/.mysqlenv"
  export PATH=${MYSQLENV_ROOT}/shims:${PATH}
  eval "$(mysqlenv init -)";
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="/usr/local/share/npm/bin:$PATH"

# for golang
export GOVERSION=1.6
export GOPATH=$HOME/.go/$GOVERSION
export PATH=$GOPATH/bin:$PATH

export PATH=$PATH:~/npm/bin
export NODE_PATH=$NODE_PATH:~/npm/lib/node_modules
export PATH=/usr/local/share/npm/bin:$PATH
export PATH=$HOME/.nodebrew/current/bin:$PATH
export NODE_PATH=$NODE_PATH::/Users/Jinda/npm/lib/node_modules:/Users/Jinda/npm/lib/node_modules:/Users/Jinda/npm/lib/node_modules
export PATH=~/.bin:$PATH
export PATH=$PATH:/usr/local/Cellar/php55/5.5.36/bin:$PATH
export PGDATA=/usr/local/var/postgres
