ZSH=$HOME/.oh-my-zsh
ZSH_THEME="miloshadzic"
source $ZSH/oh-my-zsh.sh

plugins=(git)

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# move dirs without cd
setopt AUTO_CD

# move between dirs
cdpath=(.. ~ ~/src)

# refresh
alias refresh="source dotfiles/home/zshrc"

# Brew command
alias brew="env PATH=${PATH/\/Users\/Jinda\/\.pyenv\/shims:?/} brew"

# open apps
alias vi='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
alias chrome='open -a Google\ Chrome'
alias safari='open -a Safari'
alias firefox='open -a Firefox'
alias slack='open -a Slack'
alias evernote='open -a Evernote'
alias line='open -a LINE'
alias skype='open -a Skype'
alias gyazo='open -a Gyazo'
alias skitch='open -a Skitch'
alias hipchat='open -a Hipchat'
alias photoshop='open -a Adobe\ Photoshop\ CC\ 2015'
alias illustrator='open -a Adobe\ Illustrator\ CC\ 2015'
alias notes='open -a notes'
alias wunderlist='open -a Wunderlist'
alias xcode='open -a Xcode'
alias tweetdeck='open -a TweetDeck'

# weather
alias wtokyo="curl -4 wttr.in/tokyo"

# move file to trash
alias rm="rmtrash"

# Git
alias g='git'

# git push
function github-push() {
  local repository=origin
  while true; do
    if [ "$1" = -f ]; then
      local f_option=$1; shift
    elif [ "$1" = --repo ]; then
      repository=$2; shift 2
    else break; fi
  done

  local branch=${1:-$(git rev-parse --abbrev-ref HEAD)}
  local parent_branch=${2:-master}

  git push $f_option $repository $branch \
  && github-urls $branch $parent_branch
}

function github-urls() {
  local src_branch=${1:-$(git rev-parse --abbrev-ref HEAD)}
  local dst_branch=${2:-master}
  local url=$(github-push-url)

  echo "$url "
  echo "$url/tree/$src_branch "
  if [ $src_branch != $dst_branch ]; then
    echo "$url/compare/${dst_branch}...${src_branch} "
  fi
}

function github-push-url() {
  git remote -v | grep '(push)' | awk '{print $2}' | sed -e "s/^[a-z]*@\([a-z0-9\.]*\):/https:\/\/\1\//g" | sed 's/\.git$//g'
}

alias gps='git push'
alias gpsf='git push -f'

# Unix
alias ..='cd ..'
alias t='tmux'
alias grep='grep --color=auto'

# Ruby
alias b='bundle'
alias be='bundle exec'
alias べ='bundle exec'
alias bi='bundle install'
alias び='bundle install'
alias bu='bundle update'
alias ぶ='bundle update'

if which pyenv > /dev/null; then
  export PYENV_ROOT="${HOME}/.pyenv"
  export PATH=${PYENV_ROOT}/shims:${PATH}
  eval "$(pyenv init -)";
fi
if which plenv > /dev/null; then
  export PLENV_ROOT="${HOME}/.plenv"
  export PATH=${PLENV_ROOT}/shims:${PATH}
  eval "$(plenv init -)";
fi
if which mysqlenv > /dev/null; then
  export MYSQLENV_ROOT="${HOME}/.mysqlenv"
  export PATH=${MYSQLENV_ROOT}/shims:${PATH}
  eval "$(mysqlenv init -)";
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="/usr/local/share/npm/bin:$PATH"

# for golang
export GOVERSION=1.6
export GOPATH=$HOME/.go/$GOVERSION
export PATH=$GOPATH/bin:$PATH

export PATH=$PATH:~/npm/bin
export NODE_PATH=$NODE_PATH:~/npm/lib/node_modules
export PATH=/usr/local/share/npm/bin:$PATH
export PATH=$HOME/.nodebrew/current/bin:$PATH
export NODE_PATH=$NODE_PATH::/Users/Jinda/npm/lib/node_modules:/Users/Jinda/npm/lib/node_modules:/Users/Jinda/npm/lib/node_modules
export PATH=~/.bin:$PATH
